using System.IO;
using System.Text;
using AeroMaintain.Models;

namespace AeroMaintain.Services;

public class ExportService
{
    public string ExportEquipmentCsv(IEnumerable<Equipment> equipment, string exportDirectory)
    {
        EnsureDirectory(exportDirectory);
        var path = Path.Combine(exportDirectory, $"equipment_status_{DateTime.Now:yyyyMMdd_HHmmss}.csv");

        var lines = new List<string>
        {
            "Name,SerialNumber,Category,Status,LastMaintenanceDate,MaintenanceIntervalDays,NextDueDate,RecentIssueCount,HealthScore,HealthLabel"
        };

        lines.AddRange(equipment.Select(e =>
            string.Join(",",
                EscapeCsv(e.Name),
                EscapeCsv(e.SerialNumber),
                EscapeCsv(e.Category),
                e.Status,
                e.LastMaintenanceDate.ToString("yyyy-MM-dd"),
                e.MaintenanceIntervalDays,
                e.NextDueDate.ToString("yyyy-MM-dd"),
                e.RecentIssueCount,
                e.HealthScore,
                EscapeCsv(e.HealthLabel))));

        File.WriteAllLines(path, lines, Encoding.UTF8);
        return path;
    }

    public string ExportTasksCsv(IEnumerable<MaintenanceTask> tasks, string exportDirectory)
    {
        EnsureDirectory(exportDirectory);
        var path = Path.Combine(exportDirectory, $"maintenance_tasks_{DateTime.Now:yyyyMMdd_HHmmss}.csv");

        var lines = new List<string>
        {
            "EquipmentName,SerialNumber,Category,DueDate,DaysRemaining,IsOverdue,EquipmentStatus,Priority"
        };

        lines.AddRange(tasks.Select(t =>
            string.Join(",",
                EscapeCsv(t.EquipmentName),
                EscapeCsv(t.SerialNumber),
                EscapeCsv(t.Category),
                t.DueDate.ToString("yyyy-MM-dd"),
                t.DaysRemaining,
                t.IsOverdue,
                t.EquipmentStatus,
                t.PriorityLabel)));

        File.WriteAllLines(path, lines, Encoding.UTF8);
        return path;
    }

    public string BuildTextReport(
        IEnumerable<Equipment> equipment,
        IEnumerable<MaintenanceTask> tasks,
        double averageHealthScore,
        string exportDirectory)
    {
        EnsureDirectory(exportDirectory);
        var path = Path.Combine(exportDirectory, $"maintenance_report_{DateTime.Now:yyyyMMdd_HHmmss}.txt");
        var equipmentList = equipment.ToList();
        var taskList = tasks.ToList();

        var overdueCount = taskList.Count(t => t.IsOverdue);
        var upcomingCount = taskList.Count(t => !t.IsOverdue && t.DaysRemaining <= 30);
        var healthyCount = equipmentList.Count(e => e.Status == EquipmentStatus.Healthy);
        var watchCount = equipmentList.Count(e => e.Status == EquipmentStatus.Watch);
        var criticalCount = equipmentList.Count(e => e.Status == EquipmentStatus.Critical);

        var sb = new StringBuilder();
        sb.AppendLine("AeroMaintain - Equipment Health and Maintenance Report");
        sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine(new string('-', 62));
        sb.AppendLine($"Total equipment: {equipmentList.Count}");
        sb.AppendLine($"Healthy/Watch/Critical: {healthyCount}/{watchCount}/{criticalCount}");
        sb.AppendLine($"Overdue tasks: {overdueCount}");
        sb.AppendLine($"Upcoming tasks (30 days): {upcomingCount}");
        sb.AppendLine($"Average health score: {averageHealthScore:F1}");
        sb.AppendLine();
        sb.AppendLine("Highest Priority Items:");

        var priority = taskList
            .Where(t => t.IsOverdue || t.EquipmentStatus == EquipmentStatus.Critical)
            .OrderBy(t => t.DaysRemaining)
            .Take(8)
            .ToList();

        if (priority.Count == 0)
        {
            sb.AppendLine("- No immediate priority items.");
        }
        else
        {
            foreach (var task in priority)
            {
                sb.AppendLine(
                    $"- {task.EquipmentName} ({task.SerialNumber}) | Due {task.DueDate:yyyy-MM-dd} | {task.DaysRemaining} days");
            }
        }

        sb.AppendLine();
        sb.AppendLine("Generated by AeroMaintain for local workflow and internship portfolio demonstration.");

        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        return path;
    }

    private static string EscapeCsv(string value)
    {
        if (value.Contains(',') || value.Contains('"') || value.Contains('\n'))
        {
            return $"\"{value.Replace("\"", "\"\"")}\"";
        }

        return value;
    }

    private static void EnsureDirectory(string exportDirectory)
    {
        if (!Directory.Exists(exportDirectory))
        {
            Directory.CreateDirectory(exportDirectory);
        }
    }
}
